const BUTTON_CLOSE_MODULE_WINDOW = 'Escape';
const IMAGE_DESCRIPTION_MAX_LENGTH = 140;
const IMAGE_SCALE_MIN = 25;
const IMAGE_SCALE_MAX = 100;
const IMAGE_SCALE_STEP = 25;

export {
  BUTTON_CLOSE_MODULE_WINDOW,
  IMAGE_DESCRIPTION_MAX_LENGTH,
  IMAGE_SCALE_MIN,
  IMAGE_SCALE_MAX,
  IMAGE_SCALE_STEP,
};
