const DEBOUNCE_DEFAULT_DELAY_TIME = 500;
const BUTTON_CLOSE_MODULE_WINDOW = 'Escape';
const IMAGE_DESCRIPTION_MAX_LENGTH = 140;
const FILTER_NUMBER_OF_RANDOM_IMAGES = 10;
const ImageScaleParameters = {
  IMAGE_SCALE_MIN: 25,
  IMAGE_SCALE_MAX: 100,
  IMAGE_SCALE_STEP: 25,
};

export {
  DEBOUNCE_DEFAULT_DELAY_TIME,
  FILTER_NUMBER_OF_RANDOM_IMAGES,
  BUTTON_CLOSE_MODULE_WINDOW,
  IMAGE_DESCRIPTION_MAX_LENGTH,
  ImageScaleParameters,
};
